### ISSUE TITLE
Error: no indicator is not available for my query.

### ISSUE THREAD

**Issue by d-qn** [christophergandrud/imfr#1] opened 2016-07-27 13:28 UTC
Hello,

I cannot get any data with _imf_data_ . All other imfr functions seem to work and return something. But with _imf_data()_, I always get an error. This happens with the function's example: 

```
real_ex <- imf_data(database_id = 'IFS', indicator = 'EREER_IX',
               country = c('CN', 'GB'), freq = 'A')

Error: EREER_IX is not available for your query.
```

**Comment by ulfelder** [comment] 2016-07-27 19:15
I am getting the same error message with all calls to `imf_data`. Here's the line I was trying to run:

```
UR <- imf_data(database_id = "IFS",
               indicator = "LUR_PT",
               start = 1980,
               end = lubridate::year(Sys.Date()),
               freq = 'M')
```

I tried varying the start year and the frequency and got the same error on all attempts.

**Comment by christophergandrud** [comment] 2016-08-04 11:54
Sorry about this. It appears that the IMF API is down in some way (or they introduced an undocumented change). I've been trying to get in contact with them, but have had no response yet. 

On a larger point: I created **imfr** so that I could avoid their really buggy and crashy web interface, but it looks like their API has significant bugs and crashes.

**Comment by ulfelder** [comment] 2016-08-05 11:07
Thanks. I feel your pain. That API is remarkably bad, given the resources the IMF has and the value and breadth of their data.

**Comment by christophergandrud** [comment] 2016-08-05 11:20
👍

**Comment by christophergandrud** [comment] 2016-08-08 13:39
The problem is resolved by eb19af82e52ef6bbbe5448b7873060c11ce64639 (see http://data.imf.org/?sk=A329021F-1ED6-4D6E-B719-5BF5413923B6 for details on IMF API changes). 

The current development version (0.1.1) should now work. I just submitted an update to CRAN, so hopefully that will be up soon.

**Closed by christophergandrud** 2016-08-08 13:39 UTC

**Comment by d-qn** [comment] 2016-08-08 19:30
awesome, cheers!

**Comment by ulfelder** [comment] 2016-08-09 09:27
Fantastic. Thanks so much!
